### PR TITLE
SS-221, SS-114, SS-147 SS-130, SS-163, SS-214 and SS-205 (based on feedback) 

### PR DESCRIPTION
**Pull request by marzmehr**
Changes include: 

- An admin user can upload profile picture 
- An admin user can expire user profiles  
- An admin user can view expired and active profiles  
- An admin user can search the profile list based on location/rank/full-name/badge-number  
- An admin user can view the profile identification tab  
- If a duplicate IDIR is entered during creating a profile, an error message is displayed.  
- Assigning roles to a user has been changed based on feedback received through the previous PR.

### CODE REVIEW

**Comment by seeker25** [comment]
You'll have to run db/sql/RolePermissionDefaults.sql, after letting the app start up and all the migrations execute.

**Comment by seeker25** [comment]
Looks good to me. Sent my suggestions over rocket chat.

**Comment by seeker25** [comment]
I've rolled the database back to UserRoleUnique, which is what is deployed on dev.. ran the application and it seemed to update to the latest migration no problem.

**Comment by WadeBarnes** [comment]
Get a warning about replacing the profile photo ever when there isn't one to start with; 
image

**Review by seeker25 — APPROVED** [review]

**Comment by marzmehr** [comment]
> Get a warning about replacing the profile photo ever when there isn't one to start with;
> image

good catch! Thank you @WadeBarnes

**Comment by WadeBarnes** [comment]
Also, when the photo is too large there is an error message, but there is no indication of the maximum size of the image.  Sorry for no screenshot, lost power.

**Comment by marzmehr** [comment]
> Also, when the photo is too large there is an error message, but there is no indication of the maximum size of the image. Sorry for no screenshot, lost power.

no worries, will fix this.

**Comment by marzmehr** [comment]
> > Also, when the photo is too large there is an error message, but there is no indication of the maximum size of the image. Sorry for no screenshot, lost power.
> 
> no worries, will fix this.

@WadeBarnes please let me know if there's other changes that need to be made. Thank you for the feedback :)

**Pull request merged**
