### PR TITLE
SS-151, SS-148, SS-157, SS-150, SS-155, SS-149,  SS-153, SS-156 and SS-158: Adding functionality to add, delete and view locations, leaves and trainings in User Profile

### PR DESCRIPTION
**Pull request by marzmehr**
Changes include:

- Icon is displayed on the profile list page items 5 days in advance for loanedOut and loanedIn locations 
- User is able to add locations to a user profile
- The location List is displayed in the locations tab on the user profile window
- Home Location field has been added to the 'identification' tab for creating user profile
- On editing a user, changing the selected home location, instantly changes the user's home Location and the profile is displayed in the new locations profile list page 
- Warning message is displayed if changes are made to the identification tab fields and user navigates  to another tab.
- Error messages returned via the Locations API are displayed in the UI
- Icon is displayed on the profile list page items 5 days in advance for trainings  
- User is able to add trainings to a user profile 
- The training List is displayed in the training tab on the user profile window 
- Error messages returned via the Trainings API are displayed in the UI
- Icon is displayed on the profile list page items 5 days in advance for leaves 
- User is able to add leaves to a user profile
- The leaves List is displayed in the leave tab on the user profile window
- Error messages returned via the Leaves API are displayed in the UI

Updates:

- Leaves can be deleted through the user-profile window leave tab 
- Locations can be deleted through the user-profile window location tab 
- Training can be deleted through the user-profile window training tab 
- Home Location is displayed in the user-profile Summary under user picture 
- The upcoming leaves, locations and trainings are displayed in chronological order in the icon popup lists

### CODE REVIEW

**Review by seeker25 — CHANGES_REQUESTED** [review]
Made the suggestions over RocketChat.

**Review by WadeBarnes — CHANGES_REQUESTED** [review]
Application does not start when new "Request Access" email settings are not provided.

image

Error message: `Configuration 'RequestAccessEmailAddress' is invalid or missing.`

I would expect the application to still function, other than the associated "Request Access" email functionality.

**Comment by seeker25** [comment]
Add in the secret

**Comment by WadeBarnes** [comment]
I'd recommend moving "Home Location" to the identification tab for all operations:

image

**Comment by WadeBarnes** [comment]
Should we add a confirmation when moving a user profile to a different home location?  Currently the profile is moved without warning.  This may cause confusion if it was done unintentionally, since the profile will "disappear" from the list of profiles for the currently viewed location.

**Comment by marzmehr** [comment]
> I'd recommend moving "Home Location" to the identification tab for all operations:
> 
> image

Sure Wade, I'll make the change.

**Comment by marzmehr** [comment]
> Should we add a confirmation when moving a user profile to a different home location? Currently the profile is moved without warning. This may cause confusion if it was done unintentionally, since the profile will "disappear" from the list of profiles for the currently viewed location.

Sure Wade, I'll make the change.

**Comment by WadeBarnes** [comment]
Loan popup should display dates in chronological order:

image

**Comment by WadeBarnes** [comment]
When entering time the user should be able to:
- enter the time directly rather than having to scroll through the digits.
- enter the time in 24h notation.

image

**Comment by WadeBarnes** [comment]
Unable to loan Sheriff out for a single day:

image

image

**Comment by marzmehr** [comment]
> When entering time the user should be able to:
> 
> * enter the time directly rather than having to scroll through the digits.
> * enter the time in 24h notation.
> 
> image

Sure @WadeBarnes this takes a while to implement since it will need customization and validation of the user input. I'll work on it next sprint if that's ok with you?

**Comment by seeker25** [comment]
From Oct 21, 2020 to Oct 22,2020.. that's a single day. Oct 21 to Oct21 isn't a single day.

**Comment by marzmehr** [comment]
> Loan popup should display dates in chronological order:
> 
> image

Sure, I'll make the change.

**Comment by WadeBarnes** [comment]
Leave and Training entries and records seem to be affected by the sample issues as locations.  For example, unable to add single day leave or training:

image

image

**Comment by WadeBarnes** [comment]
Overall looking good.

**Comment by marzmehr** [comment]
> I'd recommend moving "Home Location" to the identification tab for all operations:
> 
> image


> Overall looking good.

@WadeBarnes  and @seeker25 I've applied 2 of the suggestions and the delete functionality. Please take a look and let me know if you have any suggesstions. I'll include the following changes along with SS-197:

- Display confirmation message for changing the homeLocation in edit mode 
- Moving the homeLocation field to the identification tab

**Review by WadeBarnes — APPROVED** [review]

**Comment by WadeBarnes** [comment]
I'm going to get the existing changes merged and deployed.  Then follow with the reset of the updates when they are ready.

**Pull request merged**
